### PR TITLE
Update Gradle Wrapper to 7.6.1

### PR DESCRIPTION
**Pull request by dbwiddis**
### Description

Gradle versions before 7.6 are incompatible with JDK 19 and later.

Some GitHub action backend code using jackson-core 2.5.0 is failing builds because it includes an MRJAR with JDK 19 code.  See, for example, [this failed action](https://github.com/opensearch-project/search-processor/actions/runs/4803442236/jobs/8547924201#step:5:27).

There are other incompatibilities in the build for Gradle 8, so 7.6.1 is the only option to keep a working build.

This commit is the result of executing `./gradlew wrapper`.
 
### Issues Resolved
N/A
 
### Check List
- ~[ ] New functionality includes testing.~
  - ~[ ] All tests pass, including unit test, integration test and doctest~
- ~[ ] New functionality has been documented.~
  - ~[ ] New functionality has javadoc added~
  - ~[ ] New functionality has user manual doc added~
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by noCharger** [comment]
Gradle upgrade makes sense for JDK19 compatibility. Looks like this repo is using [jackson-core 2.14.2](https://github.com/opensearch-project/search-processor/blob/095d367ced1c316d7d355ea9016bd166508e5a6e/build.gradle#L89) and this caused [conflicts](https://github.com/opensearch-project/search-processor/actions/runs/4805175661/jobs/8551340124?pr=132)

@dbwiddis  shall we ungrade jackson-core as well?

**Comment by dbwiddis** [comment]
> @dbwiddis shall we ungrade jackson-core as well?

That would be my vote, but it's ultimately your call.   I generally believe repos should always update to the latest versions of dependencies for bug fixes and security fixes. You could also replace it with something else since Jackson tends to be a frequent source of CVEs. 

I'm not sure what plugin in the `build.gradle` is importing the newest Jackson, but it's common across many repos (I submitted 8 versions of this PR to repos with failing builds) and apparently upgraded about 3 days ago.  This fix doesn't really address that, it just fixes the JDK19 compatibility issue.  Your options are essentially:
 - find out what's bringing in jackson-core 2.5.0 and remove it
 - remove whatever dependency you have on an earlier version
 - upgrade your version to match
 - do nothing and let your [builds keep failing](https://github.com/opensearch-project/search-processor/actions/workflows/CI.yml) :-)

**Comment by dbwiddis** [comment]
Adding on to my recommendation for keeping dependencies up to date, [here are some options](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#keep-dependencies-up-to-date).  I personally prefer Renovate, which [we've configured in SDK Repo](https://github.com/opensearch-project/opensearch-sdk-java/blob/b30bec488ee4ac0b74fdad14d503a1e5f99482ed/.whitesource#L17-L26).

**Comment by macohen** [comment]
Thanks @dbwiddis. Can you say more about the incompatibilities with 8.1 or point us to an issue? In https://github.com/opensearch-project/search-processor/pull/134/files, we're updating Gradle to 8.1. @msfroh, if there are other incompatibilities in 8.1, will we update #134 with 7.6.1 instead of 8.1?

**Comment by dbwiddis** [comment]
> Thanks @dbwiddis. Can you say more about the incompatibilities with 8.1 or point us to an issue? 

If you look at a gradle check log in 7.6.x, like [this one](https://github.com/opensearch-project/search-processor/actions/runs/4805175661/jobs/8551340376#step:5:62) you'll see output:

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> 
> You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
> 
> See https://docs.gradle.org/7.6.1/userguide/command_line_interface.html#sec:command_line_warnings

Sometimes it's a quick fix of replacing a deprecated `build.gradle` parameter with the new one.  Sometimes it's a rabbit hole where you fix one and uncover a new one.   Isee @msfroh has already implemented some (maybe all?) of these in #134 (such as *.enabled -> *.required).   If it's building successfully on Gradle 8, it's good.

Note that #134 simply changes the download url, which means that your CI will be downloading that new version each time.   See, for example, [this log](https://github.com/opensearch-project/search-processor/actions/runs/4856370097/jobs/8655863267#step:5:9).  That costs you 13 seconds of build time! 😁 
```
2023-05-02T00:39:31.8273990Z Downloading https://services.gradle.org/distributions/gradle-8.1-all.zip
2023-05-02T00:39:34.7167200Z ................10%................20%................30%................40%................50%................60%................70%................80%................90%................100%
2023-05-02T00:39:44.1070800Z 
2023-05-02T00:39:44.1083420Z Welcome to Gradle 8.1!
```

In contrast, this PR ran `gradle wrapper` which puts a local copy of the current Gradle version's jar in the repo so it's available on checkout.  I'd suggest in #134 you run `./gradlew wrapper` to generate the new artifacts there, and then close this PR.

**Comment by msfroh** [comment]
> Note that #134 simply changes the download url, which means that your CI will be downloading that new version each time. See, for example, [this log](https://github.com/opensearch-project/search-processor/actions/runs/4856370097/jobs/8655863267#step:5:9). That costs you 13 seconds of build time!

Oh, thanks! I thought I had checked in the new jar (that I copied from core). I didn't realize that it would still download on build.

Anyway, I've run `./gradlew wrapper` over on #134, so I'll close this one out.

**Comment by dbwiddis** [comment]
> Oh, thanks! I thought I had checked in the new jar (that I copied from core). I didn't realize that it would still download on build.

Hmm, looks like it probably would have, but there was an `all` vs. `bin` mismatch.

**Pull request closed without merging**
